global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - 'alerts.yml'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  - job_name: 'doccraft-ai'
    static_configs:
      - targets: ['doccraft-ai-service:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  - job_name: 'nodejs-metrics'
    static_configs:
      - targets: ['doccraft-ai-service:8080']
    metrics_path: '/metrics/nodejs'

  - job_name: 'ai-performance'
    static_configs:
      - targets: ['doccraft-ai-service:8080']
    metrics_path: '/metrics/ai-performance'

  - job_name: 'security-metrics'
    static_configs:
      - targets: ['doccraft-ai-service:8080']
    metrics_path: '/metrics/security'
