// MCP Context Block
/*
{
  file: "modules/plotStructure/frameworkConfigs.ts",
  role: "developer",
  allowedActions: ["scaffold", "structure", "connect"],
  tier: "Pro",
  contentSensitivity: "medium",
  theme: "story_engineering"
}
*/

import type { PlotBeat } from './initPlotEngine';

export const FrameworkConfigs: Record<string, PlotBeat[]> = {
  HerosJourney: [
    {
      id: 'call',
      name: 'Call to Adventure',
      label: 'Call to Adventure',
      description: '',
      act: 1,
      position: 0.1,
      tensionLevel: 30,
      isStructural: true,
    },
    {
      id: 'mentor',
      name: 'Meeting the Mentor',
      label: 'Meeting the Mentor',
      description: '',
      act: 1,
      position: 0.2,
      tensionLevel: 20,
      isStructural: false,
    },
    {
      id: 'threshold',
      name: 'Crossing the Threshold',
      label: 'Crossing the Threshold',
      description: '',
      act: 1,
      position: 0.25,
      tensionLevel: 40,
      isStructural: true,
    },
    {
      id: 'ordeal',
      name: 'Ordeal',
      label: 'Ordeal',
      description: '',
      act: 2,
      position: 0.5,
      tensionLevel: 80,
      isStructural: true,
    },
    {
      id: 'reward',
      name: 'Reward',
      label: 'Reward',
      description: '',
      act: 2,
      position: 0.6,
      tensionLevel: 50,
      isStructural: false,
    },
    {
      id: 'roadBack',
      name: 'The Road Back',
      label: 'The Road Back',
      description: '',
      act: 2,
      position: 0.8,
      tensionLevel: 60,
      isStructural: true,
    },
    {
      id: 'resurrection',
      name: 'Resurrection',
      label: 'Resurrection',
      description: '',
      act: 3,
      position: 0.9,
      tensionLevel: 90,
      isStructural: true,
    },
    {
      id: 'return',
      name: 'Return with Elixir',
      label: 'Return with Elixir',
      description: '',
      act: 3,
      position: 1.0,
      tensionLevel: 40,
      isStructural: true,
    },
  ],
  SaveTheCat: [
    {
      id: 'opening',
      name: 'Opening Image',
      label: 'Opening Image',
      description: '',
      act: 1,
      position: 0.0,
      tensionLevel: 10,
      isStructural: true,
    },
    {
      id: 'theme',
      name: 'Theme Stated',
      label: 'Theme Stated',
      description: '',
      act: 1,
      position: 0.05,
      tensionLevel: 15,
      isStructural: false,
    },
    {
      id: 'setup',
      name: 'Set-Up',
      label: 'Set-Up',
      description: '',
      act: 1,
      position: 0.1,
      tensionLevel: 20,
      isStructural: true,
    },
    {
      id: 'catalyst',
      name: 'Catalyst',
      label: 'Catalyst',
      description: '',
      act: 1,
      position: 0.12,
      tensionLevel: 30,
      isStructural: true,
    },
    {
      id: 'debate',
      name: 'Debate',
      label: 'Debate',
      description: '',
      act: 1,
      position: 0.18,
      tensionLevel: 25,
      isStructural: false,
    },
    {
      id: 'break1',
      name: 'Break into Two',
      label: 'Break into Two',
      description: '',
      act: 2,
      position: 0.25,
      tensionLevel: 35,
      isStructural: true,
    },
    {
      id: 'bStory',
      name: 'B Story',
      label: 'B Story',
      description: '',
      act: 2,
      position: 0.3,
      tensionLevel: 20,
      isStructural: false,
    },
    {
      id: 'funGames',
      name: 'Fun and Games',
      label: 'Fun and Games',
      description: '',
      act: 2,
      position: 0.4,
      tensionLevel: 30,
      isStructural: false,
    },
    {
      id: 'midpoint',
      name: 'Midpoint',
      label: 'Midpoint',
      description: '',
      act: 2,
      position: 0.5,
      tensionLevel: 60,
      isStructural: true,
    },
    {
      id: 'badGuys',
      name: 'Bad Guys Close In',
      label: 'Bad Guys Close In',
      description: '',
      act: 2,
      position: 0.65,
      tensionLevel: 70,
      isStructural: false,
    },
    {
      id: 'allIsLost',
      name: 'All Is Lost',
      label: 'All Is Lost',
      description: '',
      act: 2,
      position: 0.75,
      tensionLevel: 90,
      isStructural: true,
    },
    {
      id: 'break3',
      name: 'Break into Three',
      label: 'Break into Three',
      description: '',
      act: 3,
      position: 0.85,
      tensionLevel: 50,
      isStructural: true,
    },
    {
      id: 'finale',
      name: 'Finale',
      label: 'Finale',
      description: '',
      act: 3,
      position: 0.95,
      tensionLevel: 80,
      isStructural: true,
    },
    {
      id: 'finalImage',
      name: 'Final Image',
      label: 'Final Image',
      description: '',
      act: 3,
      position: 1.0,
      tensionLevel: 20,
      isStructural: true,
    },
  ],
  ThreeAct: [
    {
      id: 'setup',
      name: 'Set-Up',
      label: 'Set-Up',
      description: '',
      act: 1,
      position: 0.0,
      tensionLevel: 20,
      isStructural: true,
    },
    {
      id: 'inciting',
      name: 'Inciting Incident',
      label: 'Inciting Incident',
      description: '',
      act: 1,
      position: 0.1,
      tensionLevel: 30,
      isStructural: true,
    },
    {
      id: 'firstTurn',
      name: 'First Turning Point',
      label: 'First Turning Point',
      description: '',
      act: 1,
      position: 0.25,
      tensionLevel: 40,
      isStructural: true,
    },
    {
      id: 'midpoint',
      name: 'Midpoint',
      label: 'Midpoint',
      description: '',
      act: 2,
      position: 0.5,
      tensionLevel: 60,
      isStructural: true,
    },
    {
      id: 'secondTurn',
      name: 'Second Turning Point',
      label: 'Second Turning Point',
      description: '',
      act: 2,
      position: 0.75,
      tensionLevel: 80,
      isStructural: true,
    },
    {
      id: 'climax',
      name: 'Climax',
      label: 'Climax',
      description: '',
      act: 3,
      position: 0.9,
      tensionLevel: 90,
      isStructural: true,
    },
    {
      id: 'resolution',
      name: 'Resolution',
      label: 'Resolution',
      description: '',
      act: 3,
      position: 1.0,
      tensionLevel: 30,
      isStructural: true,
    },
  ],
  Custom: [],
};
