name: Code Coverage

on:
  workflow_call:
  push:
    branches: [ main, develop, master ]
    paths:
      - 'src/**'
      - '__tests__/**'
      - 'package.json'
      - 'package-lock.json'
      - 'jest.config.js'
      - '.github/workflows/coverage.yml'
  pull_request:
    branches: [ main, develop, master ]
    paths:
      - 'src/**'
      - '__tests__/**'
      - 'package.json'
      - 'package-lock.json'
      - 'jest.config.js'
      - '.github/workflows/coverage.yml'

env:
  NODE_VERSION: '18'

jobs:
  coverage:
    name: Code Coverage Analysis
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
            
      - name: Install dependencies
        run: npm ci
        
      - name: Run tests with coverage
        run: |
          npm test -- --coverage --coverageThreshold='{"global": {"lines": 90, "functions": 85, "branches": 80}}' --passWithNoTests
        id: coverage
        env:
          NODE_ENV: test
          CI: true
        
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage/lcov.info
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
          
      - name: Upload coverage results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-results
          path: |
            coverage/
          retention-days: 30
          
      - name: Comment on PR with coverage results
        if: github.event_name == 'pull_request' && always()
        uses: actions/github-script@v7
        with:
          script: |
            // Check if coverage passed
            const coverageExitCode = process.env.COVERAGE_EXIT_CODE || '0';
            const coverageStatus = coverageExitCode === '0' ? '✅ PASSED' : '❌ FAILED';
            
            // Generate comment
            const comment = `## Coverage Results
            
            **Status:** ${coverageStatus}
            **Node Version:** ${process.env.NODE_VERSION}
            **Runner:** ${process.env.RUNNER_OS}
            
            ### Coverage Summary
            - Code coverage: ${coverageStatus}
            - Threshold: 90% lines, 85% functions, 80% branches
            
            ### Details
            Coverage reports are available as artifacts and uploaded to Codecov.
            
            ---
            *Generated by GitHub Actions*`;
            
            // Post comment
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
        env:
          COVERAGE_EXIT_CODE: ${{ steps.coverage.outputs.exit-code }} 