name: Docs Guard

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - "**/*.md"          # allow pure doc edits without rerunning if you want; remove to always run
      - "docs/**"          # docs-only changes can skip; remove to enforce always
  # Manual trigger if needed:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: docs-guard-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  verify-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history for diff)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install package manager (Corepack)
        run: corepack enable

      - name: Install deps (pnpm/yarn/npm)
        run: |
          if [ -f pnpm-lock.yaml ]; then pnpm i --frozen-lockfile;
          elif [ -f yarn.lock ]; then yarn install --frozen-lockfile;
          else npm ci;
          fi

      - name: Generate docs for changed areas (safe fallback inside script)
        run: |
          if [ -f package.json ]; then
            if npm run | grep -q "docs:changed"; then pnpm run docs:changed || npm run docs:changed || true; fi
          fi

      - name: Verify required docs exist
        run: |
          if [ -f package.json ]; then
            if npm run | grep -q "docs:verify"; then pnpm run docs:verify || npm run docs:verify; fi
          fi

      - name: Upload docs artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: docs-dev-${{ github.sha }}
          path: docs/dev
          if-no-files-found: warn
