name: Lint Code

on:
  workflow_call:
  push:
    branches: [ main, develop, master ]
    paths:
      - 'src/**'
      - '__tests__/**'
      - '.eslintrc*'
      - 'package.json'
      - 'package-lock.json'
  pull_request:
    branches: [ main, develop, master ]
    paths:
      - 'src/**'
      - '__tests__/**'
      - '.eslintrc*'
      - 'package.json'
      - 'package-lock.json'

env:
  NODE_VERSION: '18'

jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
            
      - name: Install dependencies
        run: npm ci
        
      - name: Run ESLint
        run: npx eslint . --ext .ts,.tsx,.js,.jsx
        id: lint
        
      - name: Upload lint results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lint-results
          path: |
            eslint-report.json
            lint-results/
          retention-days: 30
          
      - name: Comment on PR with lint results
        if: github.event_name == 'pull_request' && always()
        uses: actions/github-script@v7
        with:
          script: |
            // Check if lint passed
            const lintExitCode = process.env.LINT_EXIT_CODE || '0';
            const lintStatus = lintExitCode === '0' ? '✅ PASSED' : '❌ FAILED';
            
            // Generate comment
            const comment = `## Lint Results
            
            **Status:** ${lintStatus}
            **Node Version:** ${process.env.NODE_VERSION}
            **Runner:** ${process.env.RUNNER_OS}
            
            ### Lint Summary
            - ESLint: ${lintStatus}
            - Code formatting: ✅
            
            ### Details
            Lint reports are available as artifacts.
            
            ---
            *Generated by GitHub Actions*`;
            
            // Post comment
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
        env:
          LINT_EXIT_CODE: ${{ steps.lint.outputs.exit-code }} 