name: Test

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --experimental-vm-modules
      NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET || 'test-secret' }}
      NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL || 'http://localhost:3000' }}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL || 'http://localhost:54321' }}
      SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY || 'test-anon-key' }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY || 'test-openai-key' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - run: npm ci
      - name: Pre-upgrade snapshot (for audit safety)
        run: npm run pre-upgrade
      - name: Load Test Env
        run: cp config/.env.test .env.local
      - name: Run unit tests
        id: tests
        run: |
          npm test -- --ci --passWithNoTests
          echo "exit_code=$?" >> $GITHUB_OUTPUT

      - name: Comment on PR with test results
        if: github.event_name == 'pull_request' && always()
        uses: actions/github-script@v7
        with:
          script: |
            const exitCode = '${{ steps.tests.outputs.exit_code }}';
            const testStatus = exitCode === '0' ? '✅ PASSED' : '❌ FAILED';

            const comment = `## Test Results
            
            **Status:** ${testStatus}
            
            ---
            *Generated by GitHub Actions*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            }); 