name: Type Check

on:
  workflow_call:
  push:
    branches: [ main, develop, master ]
    paths:
      - 'src/**'
      - 'tsconfig.json'
      - 'package.json'
      - 'package-lock.json'
  pull_request:
    branches: [ main, develop, master ]
    paths:
      - 'src/**'
      - 'tsconfig.json'
      - 'package.json'
      - 'package-lock.json'

env:
  NODE_VERSION: '18'

jobs:
  typecheck:
    name: TypeScript Type Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
            
      - name: Install dependencies
        run: npm ci
        
      - name: Run TypeScript type checking
        id: typecheck
        run: |
          npx tsc --noEmit
          echo "exit_code=$?" >> $GITHUB_OUTPUT
        
      - name: Upload type check results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: typecheck-results
          path: |
            tsconfig-report.json
          retention-days: 30
          
      - name: Comment on PR with type check results
        if: github.event_name == 'pull_request' && always()
        uses: actions/github-script@v7
        with:
          script: |
            const exitCode = '${{ steps.typecheck.outputs.exit_code }}';
            const typecheckStatus = exitCode === '0' ? '✅ PASSED' : '❌ FAILED';
            
            // Generate comment
            const comment = `## Type Check Results
            
            **Status:** ${typecheckStatus}
            **Node Version:** ${process.env.NODE_VERSION}
            **Runner:** ${process.env.RUNNER_OS}
            
            ### Type Check Summary
            - TypeScript compilation: ${typecheckStatus}
            
            ### Details
            Type check reports are available as artifacts.
            
            ---
            *Generated by GitHub Actions*`;
            
            // Post comment
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            }); 